/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentMethodId' : [] | [bigint],
  'createdAt' : Time,
  'plateTypeId' : bigint,
  'paymentConfirmation' : [] | [PaymentConfirmation],
  'totalAmount' : bigint,
  'quantity' : bigint,
  'price' : bigint,
  'statusEvents' : Array<StatusChangeEvent>,
  'plateTypeName' : string,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'readyToDeliver' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface PaymentConfirmation {
  'utr' : string,
  'paymentMethodId' : bigint,
  'paidVia' : string,
  'paidAt' : Time,
}
export interface StatusChangeEvent {
  'status' : OrderStatus,
  'changedAt' : Time,
  'changedBy' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'createOrder' : ActorMethod<[bigint, string, bigint, bigint], Order>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderStatusTimeline' : ActorMethod<
    [bigint],
    [] | [Array<StatusChangeEvent>]
  >,
  'getPaymentConfirmation' : ActorMethod<[bigint], [] | [PaymentConfirmation]>,
  'updateOrderStatus' : ActorMethod<
    [bigint, OrderStatus, string],
    [] | [Order]
  >,
  'updatePaymentConfirmation' : ActorMethod<
    [bigint, PaymentConfirmation],
    [] | [Order]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];