/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'plateTypeId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'plateTypeName' : IDL.Text,
});

export const idlService = IDL.Service({
  'createOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat], [Order], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'plateTypeId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'plateTypeName' : IDL.Text,
  });
  
  return IDL.Service({
    'createOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [Order],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };